[gpncfg]
autoupdate-interval = 30
gateway = "94.45.227.1"
motd = '''
 ^ ^   hooot hoooot
(O,O)     from
(   )    GPN 22
-"-"-----------------

the configuration is automatically deployed.
local changes will quickly be lost. to persist
changes, update them in the nautobot instead.

this config was generated at {timestamp}
'''
nautobot-tenant = "Gulli Gulasch"
override-fan-speed = 40
output-dir = "./generated-configs"
rollback-timeout = 3
snmp-contact = "gpn-noc@lists.entropia.de"
